-- StockWear schema core tables
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Limpieza de tablas legadas (solo aplica si provienen del esquema anterior)
DROP TABLE IF EXISTS inventory_movements CASCADE;
DROP TABLE IF EXISTS product_variants CASCADE;
DROP TABLE IF EXISTS colors CASCADE;
DROP TABLE IF EXISTS sizes CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS categories CASCADE;

-- Normalizar columnas heredadas
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'usuarios'
      AND column_name = 'authUid'
  ) THEN
    ALTER TABLE usuarios RENAME COLUMN "authUid" TO auth_uid;
  END IF;
END;
$$;

-- Usuarios sincronizados con Supabase Auth
CREATE TABLE IF NOT EXISTS usuarios (
  id UUID PRIMARY KEY,
  auth_uid UUID UNIQUE,
  nombre TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  telefono TEXT,
  rol TEXT NOT NULL CHECK (rol IN ('admin', 'empleado')),
  estado TEXT NOT NULL DEFAULT 'activo',
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW()),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

CREATE INDEX IF NOT EXISTS usuarios_email_idx ON usuarios (email);
CREATE INDEX IF NOT EXISTS usuarios_auth_uid_idx ON usuarios (auth_uid);

ALTER TABLE usuarios
  ADD COLUMN IF NOT EXISTS telefono TEXT;

-- Catálogo de categorías
CREATE TABLE IF NOT EXISTS categorias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  estado TEXT NOT NULL DEFAULT 'activo'
);

-- Catálogo de tallas
CREATE TABLE IF NOT EXISTS tallas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo TEXT NOT NULL CHECK (tipo IN ('numerico', 'alfanumerico')),
  nombre TEXT NOT NULL,
  estado TEXT NOT NULL DEFAULT 'activo'
);

-- Catálogo de almacenes
CREATE TABLE IF NOT EXISTS almacenes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  direccion TEXT,
  tipo TEXT NOT NULL CHECK (tipo IN ('principal', 'sucursal')),
  estado TEXT NOT NULL DEFAULT 'activo'
);

-- Productos
CREATE TABLE IF NOT EXISTS productos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo TEXT NOT NULL UNIQUE,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  "categoriaId" BIGINT NOT NULL REFERENCES categorias(id) ON DELETE RESTRICT,
  precio NUMERIC(12, 2) NOT NULL,
  descuento NUMERIC(5, 2) NOT NULL DEFAULT 0,
  proveedor TEXT,
  imagen TEXT,
  "stockMinimo" INTEGER NOT NULL DEFAULT 0,
  estado TEXT NOT NULL DEFAULT 'activo',
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

-- Inventario por talla y almacén
CREATE TABLE IF NOT EXISTS stock (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "productoId" BIGINT NOT NULL REFERENCES productos(id) ON DELETE CASCADE,
  "tallaId" BIGINT NOT NULL REFERENCES tallas(id) ON DELETE RESTRICT,
  "almacenId" BIGINT NOT NULL REFERENCES almacenes(id) ON DELETE RESTRICT,
  cantidad INTEGER NOT NULL DEFAULT 0,
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

-- Historial de movimientos de inventario
CREATE TABLE IF NOT EXISTS "historialStock" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo TEXT NOT NULL CHECK (tipo IN ('entrada', 'salida', 'venta', 'ajuste')),
  "productoId" BIGINT NOT NULL REFERENCES productos(id) ON DELETE CASCADE,
  "tallaId" BIGINT NOT NULL REFERENCES tallas(id) ON DELETE RESTRICT,
  "almacenId" BIGINT NOT NULL REFERENCES almacenes(id) ON DELETE RESTRICT,
  cantidad INTEGER NOT NULL,
  "stockAnterior" INTEGER NOT NULL,
  "stockNuevo" INTEGER NOT NULL,
  "usuarioId" UUID REFERENCES usuarios(id),
  motivo TEXT,
  "costoUnitario" NUMERIC(12, 2),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

-- Consultas del módulo de reconocimiento visual
CREATE TABLE IF NOT EXISTS consultas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo TEXT NOT NULL CHECK (tipo IN ('reconocimiento_visual', 'manual')),
  "productoId" BIGINT REFERENCES productos(id) ON DELETE SET NULL,
  "empleadoId" UUID REFERENCES usuarios(id),
  "nivelConfianza" TEXT NOT NULL CHECK ("nivelConfianza" IN ('alto', 'medio', 'bajo')),
  resultado TEXT NOT NULL CHECK (resultado IN ('exitoso', 'fallido')),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

-- Función para mantener "updatedAt" consistente en la tabla stock
CREATE OR REPLACE FUNCTION set_stock_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updatedAt" = timezone('utc', NOW());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_stock_updated_at
BEFORE UPDATE ON stock
FOR EACH ROW
EXECUTE FUNCTION set_stock_updated_at();

-- Índices para búsquedas rápidas
CREATE INDEX IF NOT EXISTS productos_nombre_idx ON productos USING GIN (to_tsvector('spanish', nombre));
CREATE INDEX IF NOT EXISTS productos_codigo_idx ON productos (LOWER(codigo));
CREATE INDEX IF NOT EXISTS stock_producto_idx ON stock ("productoId");
CREATE INDEX IF NOT EXISTS stock_almacen_idx ON stock ("almacenId");
CREATE INDEX IF NOT EXISTS stock_talla_idx ON stock ("tallaId");
CREATE INDEX IF NOT EXISTS consultas_producto_idx ON consultas ("productoId");
CREATE INDEX IF NOT EXISTS consultas_empleado_idx ON consultas ("empleadoId");

-- Registro de ventas
CREATE TABLE IF NOT EXISTS ventas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folio TEXT NOT NULL UNIQUE,
  total NUMERIC(12, 2) NOT NULL DEFAULT 0,
  "usuarioId" UUID REFERENCES usuarios(id) ON DELETE SET NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

CREATE TABLE IF NOT EXISTS "ventasDetalle" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ventaId" BIGINT NOT NULL REFERENCES ventas(id) ON DELETE CASCADE,
  "productoId" BIGINT NOT NULL REFERENCES productos(id) ON DELETE RESTRICT,
  "stockId" BIGINT NOT NULL REFERENCES stock(id) ON DELETE RESTRICT,
  cantidad INTEGER NOT NULL CHECK (cantidad > 0),
  "precioUnitario" NUMERIC(12, 2) NOT NULL CHECK ("precioUnitario" >= 0),
  descuento NUMERIC(5, 2) NOT NULL DEFAULT 0,
  subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS ventas_folio_idx ON ventas (folio);
CREATE INDEX IF NOT EXISTS ventas_usuario_idx ON ventas ("usuarioId");
CREATE INDEX IF NOT EXISTS ventas_detalle_venta_idx ON "ventasDetalle" ("ventaId");
CREATE INDEX IF NOT EXISTS ventas_detalle_producto_idx ON "ventasDetalle" ("productoId");
