-- Añadir descripción a productos y crear tablas de ventas
ALTER TABLE productos
  ADD COLUMN IF NOT EXISTS descripcion TEXT;

CREATE TABLE IF NOT EXISTS ventas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folio TEXT NOT NULL UNIQUE,
  total NUMERIC(12, 2) NOT NULL DEFAULT 0,
  "usuarioId" UUID REFERENCES usuarios(id) ON DELETE SET NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

CREATE TABLE IF NOT EXISTS "ventasDetalle" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ventaId" BIGINT NOT NULL REFERENCES ventas(id) ON DELETE CASCADE,
  "productoId" BIGINT NOT NULL REFERENCES productos(id) ON DELETE RESTRICT,
  "stockId" BIGINT NOT NULL REFERENCES stock(id) ON DELETE RESTRICT,
  cantidad INTEGER NOT NULL CHECK (cantidad > 0),
  "precioUnitario" NUMERIC(12, 2) NOT NULL CHECK ("precioUnitario" >= 0),
  descuento NUMERIC(5, 2) NOT NULL DEFAULT 0,
  subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS ventas_folio_idx ON ventas (folio);
CREATE INDEX IF NOT EXISTS ventas_usuario_idx ON ventas ("usuarioId");
CREATE INDEX IF NOT EXISTS ventas_detalle_venta_idx ON "ventasDetalle" ("ventaId");
CREATE INDEX IF NOT EXISTS ventas_detalle_producto_idx ON "ventasDetalle" ("productoId");

ALTER TABLE ventas ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ventasDetalle" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "ventas_select_authenticated" ON ventas;
DROP POLICY IF EXISTS "ventas_write_authenticated" ON ventas;
DROP POLICY IF EXISTS "ventas_detalle_select_authenticated" ON "ventasDetalle";
DROP POLICY IF EXISTS "ventas_detalle_write_authenticated" ON "ventasDetalle";

CREATE POLICY "ventas_select_authenticated" ON ventas
  FOR SELECT
  USING (auth.uid() IS NOT NULL);

CREATE POLICY "ventas_write_authenticated" ON ventas
  FOR ALL
  USING (auth.uid() IS NOT NULL)
  WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "ventas_detalle_select_authenticated" ON "ventasDetalle"
  FOR SELECT
  USING (auth.uid() IS NOT NULL);

CREATE POLICY "ventas_detalle_write_authenticated" ON "ventasDetalle"
  FOR ALL
  USING (auth.uid() IS NOT NULL)
  WITH CHECK (auth.uid() IS NOT NULL);
