-- Tabla para almacenar embeddings de productos (calzado)
CREATE TABLE IF NOT EXISTS producto_embeddings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "productoId" BIGINT NOT NULL REFERENCES productos(id) ON DELETE CASCADE,
  embedding DOUBLE PRECISION[] NOT NULL,
  fuente TEXT,
  "referenceImageId" BIGINT REFERENCES public.producto_reference_images(id),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW()),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

alter table public.producto_reference_images
  add column if not exists bucket text,
  add column if not exists filename text,
  add column if not exists "mimeType" text,
  add column if not exists size bigint;

alter table public.producto_embeddings
  add column if not exists "referenceImageId" bigint references public.producto_reference_images(id);

CREATE INDEX IF NOT EXISTS producto_embeddings_producto_idx ON producto_embeddings ("productoId");
CREATE INDEX IF NOT EXISTS producto_embeddings_reference_idx ON producto_embeddings ("referenceImageId");

CREATE OR REPLACE FUNCTION set_producto_embedding_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updatedAt" = timezone('utc', NOW());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_producto_embedding_updated_at ON producto_embeddings;
CREATE TRIGGER trg_producto_embedding_updated_at
BEFORE UPDATE ON producto_embeddings
FOR EACH ROW
EXECUTE FUNCTION set_producto_embedding_updated_at();
