-- Tabla para almacenar embeddings de productos (calzado)
CREATE TABLE IF NOT EXISTS producto_embeddings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "productoId" BIGINT NOT NULL REFERENCES productos(id) ON DELETE CASCADE,
  embedding DOUBLE PRECISION[] NOT NULL,
  fuente TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW()),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

CREATE INDEX IF NOT EXISTS producto_embeddings_producto_idx ON producto_embeddings ("productoId");

CREATE OR REPLACE FUNCTION set_producto_embedding_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updatedAt" = timezone('utc', NOW());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_producto_embedding_updated_at ON producto_embeddings;
CREATE TRIGGER trg_producto_embedding_updated_at
BEFORE UPDATE ON producto_embeddings
FOR EACH ROW
EXECUTE FUNCTION set_producto_embedding_updated_at();

ALTER TABLE producto_embeddings ENABLE ROW LEVEL SECURITY;

-- Políticas: lectura para autenticados, escritura únicamente para admins del sistema
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'producto_embeddings'
      AND policyname = 'producto_embeddings_select_authenticated'
  ) THEN
    CREATE POLICY "producto_embeddings_select_authenticated"
      ON producto_embeddings
      FOR SELECT
      USING (auth.uid() IS NOT NULL);
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'producto_embeddings'
      AND policyname = 'producto_embeddings_insert_admin'
  ) THEN
    CREATE POLICY "producto_embeddings_insert_admin"
      ON producto_embeddings
      FOR INSERT
      WITH CHECK (
        EXISTS (
          SELECT 1
          FROM usuarios u
          WHERE u.id = auth.uid()
            AND u.rol = 'admin'
        )
      );
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'producto_embeddings'
      AND policyname = 'producto_embeddings_update_admin'
  ) THEN
    CREATE POLICY "producto_embeddings_update_admin"
      ON producto_embeddings
      FOR UPDATE
      USING (
        EXISTS (
          SELECT 1
          FROM usuarios u
          WHERE u.id = auth.uid()
            AND u.rol = 'admin'
        )
      )
      WITH CHECK (
        EXISTS (
          SELECT 1
          FROM usuarios u
          WHERE u.id = auth.uid()
            AND u.rol = 'admin'
        )
      );
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'producto_embeddings'
      AND policyname = 'producto_embeddings_delete_admin'
  ) THEN
    CREATE POLICY "producto_embeddings_delete_admin"
      ON producto_embeddings
      FOR DELETE
      USING (
        EXISTS (
          SELECT 1
          FROM usuarios u
          WHERE u.id = auth.uid()
            AND u.rol = 'admin'
        )
      );
  END IF;
END;
$$;
