-- 1. Create Tiendas table
CREATE TABLE IF NOT EXISTS tiendas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL, -- For URL routing (e.g., stockwear.com/nike-store)
  logo_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Add tienda_id to existing tables
DO $$
BEGIN
  -- Standard tables
  EXECUTE 'ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS tienda_id BIGINT REFERENCES tiendas(id)';
  EXECUTE 'ALTER TABLE productos ADD COLUMN IF NOT EXISTS tienda_id BIGINT REFERENCES tiendas(id)';
  EXECUTE 'ALTER TABLE categorias ADD COLUMN IF NOT EXISTS tienda_id BIGINT REFERENCES tiendas(id)';
  EXECUTE 'ALTER TABLE tallas ADD COLUMN IF NOT EXISTS tienda_id BIGINT REFERENCES tiendas(id)';
  EXECUTE 'ALTER TABLE almacenes ADD COLUMN IF NOT EXISTS tienda_id BIGINT REFERENCES tiendas(id)';
  EXECUTE 'ALTER TABLE stock ADD COLUMN IF NOT EXISTS tienda_id BIGINT REFERENCES tiendas(id)';
  EXECUTE 'ALTER TABLE ventas ADD COLUMN IF NOT EXISTS tienda_id BIGINT REFERENCES tiendas(id)';
  EXECUTE 'ALTER TABLE consultas ADD COLUMN IF NOT EXISTS tienda_id BIGINT REFERENCES tiendas(id)';
  
  -- Quoted tables (Case sensitive)
  EXECUTE 'ALTER TABLE "historialStock" ADD COLUMN IF NOT EXISTS tienda_id BIGINT REFERENCES tiendas(id)';
  EXECUTE 'ALTER TABLE "ventasDetalle" ADD COLUMN IF NOT EXISTS tienda_id BIGINT REFERENCES tiendas(id)';
  EXECUTE 'ALTER TABLE producto_reference_images ADD COLUMN IF NOT EXISTS tienda_id BIGINT REFERENCES tiendas(id)';
END $$;

-- 3. Enable RLS on all tables (if not already enabled)
ALTER TABLE tiendas ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE tallas ENABLE ROW LEVEL SECURITY;
ALTER TABLE almacenes ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock ENABLE ROW LEVEL SECURITY;
ALTER TABLE ventas ENABLE ROW LEVEL SECURITY;
ALTER TABLE consultas ENABLE ROW LEVEL SECURITY;
ALTER TABLE "historialStock" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ventasDetalle" ENABLE ROW LEVEL SECURITY;
ALTER TABLE producto_reference_images ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS Policies

-- Helper function to get current user's tienda_id
CREATE OR REPLACE FUNCTION get_my_tienda_id()
RETURNS BIGINT AS $$
  SELECT tienda_id FROM usuarios WHERE auth_uid = auth.uid() LIMIT 1;
$$ LANGUAGE sql SECURITY DEFINER;

-- Policy for Tiendas: Users can view their own tienda
DROP POLICY IF EXISTS "Users can view their own tienda" ON tiendas;
CREATE POLICY "Users can view their own tienda" ON tiendas
  FOR SELECT USING (id = get_my_tienda_id());

-- Generic Policy Generator for other tables
-- "Users can view/edit records where tienda_id matches their own"
DO $$
DECLARE
  t text;
BEGIN
  -- Standard tables
  FOR t IN 
    SELECT unnest(ARRAY['productos', 'categorias', 'tallas', 'almacenes', 'stock', 'ventas', 'consultas', 'producto_reference_images'])
  LOOP
    EXECUTE format('
      DROP POLICY IF EXISTS "Tenant Isolation" ON %I;
      CREATE POLICY "Tenant Isolation" ON %I
      USING (tienda_id = get_my_tienda_id())
      WITH CHECK (tienda_id = get_my_tienda_id());
    ', t, t);
  END LOOP;
  
  -- Handle quoted tables separately
  EXECUTE 'DROP POLICY IF EXISTS "Tenant Isolation" ON "historialStock"';
  EXECUTE 'CREATE POLICY "Tenant Isolation" ON "historialStock" USING (tienda_id = get_my_tienda_id()) WITH CHECK (tienda_id = get_my_tienda_id())';
  
  EXECUTE 'DROP POLICY IF EXISTS "Tenant Isolation" ON "ventasDetalle"';
  EXECUTE 'CREATE POLICY "Tenant Isolation" ON "ventasDetalle" USING (tienda_id = get_my_tienda_id()) WITH CHECK (tienda_id = get_my_tienda_id())';

END $$;

-- Special Policy for Usuarios: Users can view other users in the same tienda
DROP POLICY IF EXISTS "Tenant Isolation" ON usuarios;
CREATE POLICY "Tenant Isolation" ON usuarios
  USING (tienda_id = (SELECT tienda_id FROM usuarios WHERE auth_uid = auth.uid() LIMIT 1))
  WITH CHECK (tienda_id = (SELECT tienda_id FROM usuarios WHERE auth_uid = auth.uid() LIMIT 1));

-- 5. Seed a default store and backfill data
INSERT INTO tiendas (nombre, slug) VALUES ('Tienda Principal', 'main') ON CONFLICT (slug) DO NOTHING;

-- Update existing records to belong to the default store (Safe to run multiple times)
DO $$
DECLARE
  main_tienda_id BIGINT;
BEGIN
  SELECT id INTO main_tienda_id FROM tiendas WHERE slug = 'main';
  
  IF main_tienda_id IS NOT NULL THEN
    UPDATE usuarios SET tienda_id = main_tienda_id WHERE tienda_id IS NULL;
    UPDATE productos SET tienda_id = main_tienda_id WHERE tienda_id IS NULL;
    UPDATE categorias SET tienda_id = main_tienda_id WHERE tienda_id IS NULL;
    UPDATE tallas SET tienda_id = main_tienda_id WHERE tienda_id IS NULL;
    UPDATE almacenes SET tienda_id = main_tienda_id WHERE tienda_id IS NULL;
    UPDATE stock SET tienda_id = main_tienda_id WHERE tienda_id IS NULL;
    UPDATE ventas SET tienda_id = main_tienda_id WHERE tienda_id IS NULL;
    UPDATE consultas SET tienda_id = main_tienda_id WHERE tienda_id IS NULL;
    UPDATE "historialStock" SET tienda_id = main_tienda_id WHERE tienda_id IS NULL;
    UPDATE "ventasDetalle" SET tienda_id = main_tienda_id WHERE tienda_id IS NULL;
    UPDATE producto_reference_images SET tienda_id = main_tienda_id WHERE tienda_id IS NULL;
  END IF;
END $$;
