-- Create Clientes table
create table if not exists public.clientes (
  id bigint generated by default as identity primary key,
  tienda_id bigint not null,
  nombre text not null,
  documento text,
  telefono text,
  direccion text,
  email text,
  limite_credito numeric default 0,
  saldo_actual numeric default 0,
  estado text default 'activo' check (estado in ('activo', 'inactivo')),
  "createdAt" timestamp with time zone default timezone('utc'::text, now()) not null,
  "updatedAt" timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Abonos table
create table if not exists public.abonos (
  id bigint generated by default as identity primary key,
  tienda_id bigint not null,
  cliente_id bigint references public.clientes(id),
  venta_id bigint references public.ventas(id), -- Optional, if linked to specific sale
  monto numeric not null check (monto > 0),
  metodo_pago_id bigint, -- Link to payment method
  usuario_id uuid references auth.users(id), -- Who registered the payment
  nota text,
  "createdAt" timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add columns to Ventas table
alter table public.ventas 
add column if not exists cliente_id bigint references public.clientes(id),
add column if not exists tipo_venta text default 'contado' check (tipo_venta in ('contado', 'credito')),
add column if not exists saldo_pendiente numeric default 0;

-- RLS Policies (Assuming standard RLS setup based on tienda_id)
alter table public.clientes enable row level security;
alter table public.abonos enable row level security;

create policy "Enable read access for all users" on public.clientes
  for select using (true);

create policy "Enable insert for authenticated users only" on public.clientes
  for insert with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only" on public.clientes
  for update using (auth.role() = 'authenticated');

create policy "Enable read access for all users" on public.abonos
  for select using (true);

create policy "Enable insert for authenticated users only" on public.abonos
  for insert with check (auth.role() = 'authenticated');
