-- Restore missing Cash Register and Payment Method schema

-- 1. Create Metodos de Pago table
CREATE TABLE IF NOT EXISTS public.metodos_pago (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tienda_id BIGINT NOT NULL REFERENCES public.tiendas(id),
  nombre TEXT NOT NULL,
  tipo TEXT NOT NULL CHECK (tipo IN ('efectivo', 'banco', 'tarjeta', 'otro')),
  estado TEXT NOT NULL DEFAULT 'activo' CHECK (estado IN ('activo', 'inactivo')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

-- Enable RLS for metodos_pago
ALTER TABLE public.metodos_pago ENABLE ROW LEVEL SECURITY;

-- RLS Policy for metodos_pago
DROP POLICY IF EXISTS "Tenant Isolation" ON public.metodos_pago;
CREATE POLICY "Tenant Isolation" ON public.metodos_pago
  USING (tienda_id = get_my_tienda_id())
  WITH CHECK (tienda_id = get_my_tienda_id());


-- 2. Create Caja Sesiones table
CREATE TABLE IF NOT EXISTS public.caja_sesiones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tienda_id BIGINT NOT NULL REFERENCES public.tiendas(id),
  usuario_id UUID NOT NULL REFERENCES public.usuarios(id),
  monto_inicial NUMERIC(12, 2) NOT NULL DEFAULT 0,
  monto_final_esperado NUMERIC(12, 2),
  monto_final_real NUMERIC(12, 2),
  diferencia NUMERIC(12, 2),
  fecha_apertura TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW()),
  fecha_cierre TIMESTAMPTZ,
  estado TEXT NOT NULL DEFAULT 'abierta' CHECK (estado IN ('abierta', 'cerrada'))
);

-- Enable RLS for caja_sesiones
ALTER TABLE public.caja_sesiones ENABLE ROW LEVEL SECURITY;

-- RLS Policy for caja_sesiones
DROP POLICY IF EXISTS "Tenant Isolation" ON public.caja_sesiones;
CREATE POLICY "Tenant Isolation" ON public.caja_sesiones
  USING (tienda_id = get_my_tienda_id())
  WITH CHECK (tienda_id = get_my_tienda_id());


-- 3. Add columns to Ventas table
ALTER TABLE public.ventas
  ADD COLUMN IF NOT EXISTS metodo_pago_id BIGINT REFERENCES public.metodos_pago(id),
  ADD COLUMN IF NOT EXISTS caja_sesion_id BIGINT REFERENCES public.caja_sesiones(id);

-- 4. Add index for performance
CREATE INDEX IF NOT EXISTS ventas_caja_sesion_idx ON public.ventas(caja_sesion_id);
CREATE INDEX IF NOT EXISTS ventas_metodo_pago_idx ON public.ventas(metodo_pago_id);
