-- 001_schema.sql
-- Consolidated Schema Migration
-- Includes: Extensions, Tables, Indexes, Foreign Keys

-- 1. Extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "postgis";

-- 2. Tables

-- Tiendas (Multi-tenancy root)
CREATE TABLE IF NOT EXISTS tiendas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  logo_url TEXT,
  whatsapp TEXT,
  owner_id UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Usuarios
CREATE TABLE IF NOT EXISTS usuarios (
  id UUID PRIMARY KEY,
  auth_uid UUID UNIQUE,
  nombre TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  telefono TEXT,
  rol TEXT NOT NULL CHECK (rol IN ('admin', 'empleado')),
  estado TEXT NOT NULL DEFAULT 'activo',
  tienda_id BIGINT REFERENCES tiendas(id),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW()),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

-- Categorias
CREATE TABLE IF NOT EXISTS categorias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  estado TEXT NOT NULL DEFAULT 'activo',
  tienda_id BIGINT REFERENCES tiendas(id)
);

-- Tallas
CREATE TABLE IF NOT EXISTS tallas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo TEXT NOT NULL CHECK (tipo IN ('numerico', 'alfanumerico')),
  nombre TEXT NOT NULL,
  estado TEXT NOT NULL DEFAULT 'activo',
  tienda_id BIGINT REFERENCES tiendas(id)
);

-- Almacenes
CREATE TABLE IF NOT EXISTS almacenes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  direccion TEXT,
  tipo TEXT NOT NULL CHECK (tipo IN ('principal', 'sucursal')),
  estado TEXT NOT NULL DEFAULT 'activo',
  latitud DOUBLE PRECISION,
  longitud DOUBLE PRECISION,
  geom geography(Point, 4326),
  tienda_id BIGINT REFERENCES tiendas(id)
);

-- Productos
CREATE TABLE IF NOT EXISTS productos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo TEXT NOT NULL UNIQUE,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  "categoriaId" BIGINT NOT NULL REFERENCES categorias(id) ON DELETE RESTRICT,
  precio NUMERIC(12, 2) NOT NULL,
  precio_base NUMERIC(12, 2) DEFAULT 0,
  descuento NUMERIC(5, 2) NOT NULL DEFAULT 0,
  proveedor TEXT,
  imagen TEXT,
  "stockMinimo" INTEGER NOT NULL DEFAULT 0,
  estado TEXT NOT NULL DEFAULT 'activo',
  tienda_id BIGINT REFERENCES tiendas(id),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

-- Ensure precio_base exists even if table was already created
DO $$
BEGIN
    ALTER TABLE productos ADD COLUMN IF NOT EXISTS precio_base NUMERIC(12, 2) DEFAULT 0;
EXCEPTION
    WHEN duplicate_column THEN RAISE NOTICE 'column precio_base already exists in productos.';
END $$;

-- Producto Reference Images
CREATE TABLE IF NOT EXISTS producto_reference_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "productoId" BIGINT NOT NULL REFERENCES productos(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  path TEXT NOT NULL,
  bucket TEXT,
  filename TEXT,
  "mimeType" TEXT,
  size BIGINT,
  tienda_id BIGINT REFERENCES tiendas(id),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW()),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

-- Producto Embeddings
CREATE TABLE IF NOT EXISTS producto_embeddings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "productoId" BIGINT NOT NULL REFERENCES productos(id) ON DELETE CASCADE,
  embedding DOUBLE PRECISION[] NOT NULL,
  fuente TEXT,
  "referenceImageId" BIGINT REFERENCES producto_reference_images(id),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW()),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

-- Stock
CREATE TABLE IF NOT EXISTS stock (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "productoId" BIGINT NOT NULL REFERENCES productos(id) ON DELETE CASCADE,
  "tallaId" BIGINT REFERENCES tallas(id) ON DELETE RESTRICT, -- Nullable per migration 011
  "almacenId" BIGINT NOT NULL REFERENCES almacenes(id) ON DELETE RESTRICT,
  cantidad INTEGER NOT NULL DEFAULT 0,
  tienda_id BIGINT REFERENCES tiendas(id),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

-- Historial Stock
CREATE TABLE IF NOT EXISTS "historialStock" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo TEXT NOT NULL CHECK (tipo IN ('entrada', 'salida', 'venta', 'ajuste')),
  "productoId" BIGINT NOT NULL REFERENCES productos(id) ON DELETE CASCADE,
  "tallaId" BIGINT REFERENCES tallas(id) ON DELETE RESTRICT, -- Nullable per migration 011
  "almacenId" BIGINT NOT NULL REFERENCES almacenes(id) ON DELETE RESTRICT,
  cantidad INTEGER NOT NULL,
  "stockAnterior" INTEGER NOT NULL,
  "stockNuevo" INTEGER NOT NULL,
  "usuarioId" UUID REFERENCES usuarios(id),
  motivo TEXT,
  "costoUnitario" NUMERIC(12, 2),
  tienda_id BIGINT REFERENCES tiendas(id),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

-- Consultas (Visual Recognition)
CREATE TABLE IF NOT EXISTS consultas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo TEXT NOT NULL CHECK (tipo IN ('reconocimiento_visual', 'manual')),
  "productoId" BIGINT REFERENCES productos(id) ON DELETE SET NULL,
  "empleadoId" UUID REFERENCES usuarios(id),
  "nivelConfianza" TEXT NOT NULL CHECK ("nivelConfianza" IN ('alto', 'medio', 'bajo')),
  resultado TEXT NOT NULL CHECK (resultado IN ('exitoso', 'fallido')),
  tienda_id BIGINT REFERENCES tiendas(id),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

-- Metodos de Pago
CREATE TABLE IF NOT EXISTS metodos_pago (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tienda_id BIGINT NOT NULL REFERENCES tiendas(id),
  nombre TEXT NOT NULL,
  tipo TEXT NOT NULL CHECK (tipo IN ('efectivo', 'digital', 'banco', 'tarjeta', 'otro')),
  estado TEXT NOT NULL DEFAULT 'activo',
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

-- Clientes
CREATE TABLE IF NOT EXISTS clientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tienda_id BIGINT NOT NULL REFERENCES tiendas(id),
  nombre TEXT NOT NULL,
  documento TEXT,
  telefono TEXT,
  direccion TEXT,
  email TEXT,
  limite_credito NUMERIC DEFAULT 0,
  saldo_actual NUMERIC DEFAULT 0,
  estado TEXT DEFAULT 'activo' CHECK (estado IN ('activo', 'inactivo')),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW()),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

-- Ventas
CREATE TABLE IF NOT EXISTS ventas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folio TEXT NOT NULL UNIQUE,
  total NUMERIC(12, 2) NOT NULL DEFAULT 0,
  "usuarioId" UUID REFERENCES usuarios(id) ON DELETE SET NULL,
  tienda_id BIGINT REFERENCES tiendas(id),
  cliente_id BIGINT REFERENCES clientes(id),
  tipo_venta TEXT DEFAULT 'contado' CHECK (tipo_venta IN ('contado', 'credito')),
  saldo_pendiente NUMERIC DEFAULT 0,
  numero_cuotas INTEGER DEFAULT 1,
  interes_porcentaje NUMERIC DEFAULT 0,
  monto_cuota NUMERIC DEFAULT 0,
  frecuencia_pago TEXT CHECK (frecuencia_pago IN ('semanal', 'mensual')),
  fecha_primer_vencimiento TIMESTAMPTZ,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

-- Ventas Detalle
CREATE TABLE IF NOT EXISTS "ventasDetalle" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ventaId" BIGINT NOT NULL REFERENCES ventas(id) ON DELETE CASCADE,
  "productoId" BIGINT NOT NULL REFERENCES productos(id) ON DELETE RESTRICT,
  "stockId" BIGINT NOT NULL REFERENCES stock(id) ON DELETE RESTRICT,
  cantidad INTEGER NOT NULL CHECK (cantidad > 0),
  "precioUnitario" NUMERIC(12, 2) NOT NULL CHECK ("precioUnitario" >= 0),
  "costoUnitario" NUMERIC(12, 2) DEFAULT 0,
  descuento NUMERIC(5, 2) NOT NULL DEFAULT 0,
  subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0,
  tienda_id BIGINT REFERENCES tiendas(id)
);

-- Ensure costoUnitario exists even if table was already created
DO $$
BEGIN
    ALTER TABLE "ventasDetalle" ADD COLUMN IF NOT EXISTS "costoUnitario" NUMERIC(12, 2) DEFAULT 0;
EXCEPTION
    WHEN duplicate_column THEN RAISE NOTICE 'column costoUnitario already exists in ventasDetalle.';
END $$;

-- Abonos
CREATE TABLE IF NOT EXISTS abonos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tienda_id BIGINT NOT NULL REFERENCES tiendas(id),
  cliente_id BIGINT REFERENCES clientes(id),
  venta_id BIGINT REFERENCES ventas(id),
  monto NUMERIC NOT NULL CHECK (monto > 0),
  metodo_pago_id BIGINT,
  usuario_id UUID REFERENCES auth.users(id),
  nota TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

-- Gastos
CREATE TABLE IF NOT EXISTS "public"."gastos" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "tienda_id" BIGINT NOT NULL,
    "usuario_id" UUID NULL,
    "caja_sesion_id" BIGINT NULL,
    "descripcion" TEXT NOT NULL,
    "monto" NUMERIC NOT NULL,
    "categoria" TEXT NOT NULL, -- 'Arriendo', 'Nómina', etc.
    "metodo_pago" TEXT NOT NULL, -- 'Efectivo', 'Tarjeta', 'Transferencia', etc.
    "proveedor" TEXT NULL,
    "estado" TEXT NOT NULL DEFAULT 'pagado', -- 'pagado', 'pendiente'
    "saldo_pendiente" NUMERIC NOT NULL DEFAULT 0,
    "fecha_vencimiento" TIMESTAMPTZ NULL,
    "fecha_gasto" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Pagos Gastos
CREATE TABLE IF NOT EXISTS "public"."pagos_gastos" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "tienda_id" BIGINT NOT NULL,
    "gasto_id" BIGINT NOT NULL REFERENCES "public"."gastos"("id") ON DELETE CASCADE,
    "usuario_id" UUID NULL,
    "caja_sesion_id" BIGINT NULL,
    "monto" NUMERIC NOT NULL,
    "metodo_pago" TEXT NOT NULL, -- 'Efectivo', 'Transferencia', 'Otro'
    "nota" TEXT NULL,
    "fecha_pago" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Indexes
CREATE INDEX IF NOT EXISTS usuarios_email_idx ON usuarios (email);
CREATE INDEX IF NOT EXISTS usuarios_auth_uid_idx ON usuarios (auth_uid);

CREATE INDEX IF NOT EXISTS productos_nombre_idx ON productos USING GIN (to_tsvector('spanish', nombre));
CREATE INDEX IF NOT EXISTS productos_codigo_idx ON productos (LOWER(codigo));

CREATE INDEX IF NOT EXISTS stock_producto_idx ON stock ("productoId");
CREATE INDEX IF NOT EXISTS stock_almacen_idx ON stock ("almacenId");
CREATE INDEX IF NOT EXISTS stock_talla_idx ON stock ("tallaId");

CREATE INDEX IF NOT EXISTS consultas_producto_idx ON consultas ("productoId");
CREATE INDEX IF NOT EXISTS consultas_empleado_idx ON consultas ("empleadoId");

CREATE INDEX IF NOT EXISTS producto_reference_images_producto_idx ON producto_reference_images ("productoId");

CREATE INDEX IF NOT EXISTS producto_embeddings_producto_idx ON producto_embeddings ("productoId");
CREATE INDEX IF NOT EXISTS producto_embeddings_reference_idx ON producto_embeddings ("referenceImageId");

CREATE INDEX IF NOT EXISTS ventas_folio_idx ON ventas (folio);
CREATE INDEX IF NOT EXISTS ventas_usuario_idx ON ventas ("usuarioId");

CREATE INDEX IF NOT EXISTS ventas_detalle_venta_idx ON "ventasDetalle" ("ventaId");
CREATE INDEX IF NOT EXISTS ventas_detalle_producto_idx ON "ventasDetalle" ("productoId");

CREATE INDEX IF NOT EXISTS idx_almacenes_lat_long ON almacenes (latitud, longitud);
CREATE INDEX IF NOT EXISTS idx_almacenes_geom ON almacenes USING GIST (geom);

-- 4. Metodos de Pago (Consolidated from 017)
CREATE TABLE IF NOT EXISTS metodos_pago (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tienda_id BIGINT NOT NULL REFERENCES tiendas(id),
  nombre TEXT NOT NULL,
  tipo TEXT NOT NULL CHECK (tipo IN ('efectivo', 'digital', 'banco', 'tarjeta', 'otro')),
  estado TEXT NOT NULL DEFAULT 'activo' CHECK (estado IN ('activo', 'inactivo')),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

-- 5. Caja Sesiones (Consolidated from 017)
CREATE TABLE IF NOT EXISTS caja_sesiones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tienda_id BIGINT NOT NULL REFERENCES tiendas(id),
  usuario_id UUID NOT NULL REFERENCES usuarios(id),
  monto_inicial NUMERIC(12, 2) NOT NULL DEFAULT 0,
  monto_final_esperado NUMERIC(12, 2),
  monto_final_real NUMERIC(12, 2),
  diferencia NUMERIC(12, 2),
  fecha_apertura TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW()),
  fecha_cierre TIMESTAMPTZ,
  estado TEXT NOT NULL DEFAULT 'abierta' CHECK (estado IN ('abierta', 'cerrada'))
);

-- 6. Schema Updates (Consolidated from 016, 017, 019)

-- Add columns to Ventas
ALTER TABLE ventas
  ADD COLUMN IF NOT EXISTS metodo_pago_id BIGINT REFERENCES metodos_pago(id),
  ADD COLUMN IF NOT EXISTS caja_sesion_id BIGINT REFERENCES caja_sesiones(id);

-- Add columns to Abonos
ALTER TABLE abonos
  ADD COLUMN IF NOT EXISTS caja_sesion_id BIGINT REFERENCES caja_sesiones(id);

-- Indexes for new columns
CREATE INDEX IF NOT EXISTS ventas_caja_sesion_idx ON ventas(caja_sesion_id);
CREATE INDEX IF NOT EXISTS ventas_metodo_pago_idx ON ventas(metodo_pago_id);
CREATE INDEX IF NOT EXISTS abonos_caja_sesion_idx ON abonos(caja_sesion_id);

-- Fix Deletion Constraints (Consolidated from 016)
-- Abonos
ALTER TABLE abonos DROP CONSTRAINT IF EXISTS abonos_usuario_id_fkey;
ALTER TABLE abonos ADD CONSTRAINT abonos_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES auth.users(id) ON DELETE SET NULL;

-- HistorialStock
ALTER TABLE "historialStock" DROP CONSTRAINT IF EXISTS "historialStock_usuarioId_fkey";
ALTER TABLE "historialStock" ADD CONSTRAINT "historialStock_usuarioId_fkey" FOREIGN KEY ("usuarioId") REFERENCES usuarios(id) ON DELETE SET NULL;

-- Consultas
ALTER TABLE consultas DROP CONSTRAINT IF EXISTS "consultas_empleadoId_fkey";
ALTER TABLE consultas ADD CONSTRAINT "consultas_empleadoId_fkey" FOREIGN KEY ("empleadoId") REFERENCES usuarios(id) ON DELETE SET NULL;

-- Usuarios (Cascade delete from auth.users)
ALTER TABLE usuarios DROP CONSTRAINT IF EXISTS usuarios_id_fkey;
ALTER TABLE usuarios ADD CONSTRAINT usuarios_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

-- Ventas
ALTER TABLE ventas DROP CONSTRAINT IF EXISTS "ventas_usuarioId_fkey";
ALTER TABLE ventas ADD CONSTRAINT "ventas_usuarioId_fkey" FOREIGN KEY ("usuarioId") REFERENCES usuarios(id) ON DELETE SET NULL;

-- Tiendas
ALTER TABLE tiendas DROP CONSTRAINT IF EXISTS tiendas_owner_id_fkey;
ALTER TABLE tiendas ADD CONSTRAINT tiendas_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE SET NULL;

-- =============================================================================
-- 7. Sleep Schedule Configuration (Consolidated from 020)
-- =============================================================================

ALTER TABLE tiendas
  ADD COLUMN IF NOT EXISTS sleep_schedule_enabled BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS sleep_schedule_time TIME DEFAULT '22:00:00',
  ADD COLUMN IF NOT EXISTS wake_schedule_time TIME DEFAULT '07:00:00';

COMMENT ON COLUMN tiendas.sleep_schedule_enabled IS 'Indica si la desactivación automática de cuentas está habilitada';
COMMENT ON COLUMN tiendas.sleep_schedule_time IS 'Hora del día en que se desactivan automáticamente las cuentas (excepto el propietario)';
COMMENT ON COLUMN tiendas.wake_schedule_time IS 'Hora del día en que se permite nuevamente el acceso (fin del modo dormir)';

-- =============================================================================
-- 8. Visual Recognition Feedback (Consolidated from 023)
-- =============================================================================

CREATE TABLE IF NOT EXISTS visual_recognition_feedback (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  -- Relaciones
  tienda_id INTEGER REFERENCES tiendas(id) ON DELETE CASCADE,
  empleado_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  producto_sugerido_id INTEGER REFERENCES productos(id) ON DELETE SET NULL,
  producto_correcto_id INTEGER REFERENCES productos(id) ON DELETE SET NULL,
  
  -- Datos del reconocimiento
  similitud FLOAT NOT NULL,
  umbral FLOAT NOT NULL,
  fue_correcto BOOLEAN NOT NULL,
  
  -- El embedding capturado (opcional, para análisis futuro)
  embedding FLOAT8[] DEFAULT NULL,
  
  -- Metadata adicional (nivel de confianza, timestamp original, etc.)
  metadata JSONB DEFAULT '{}'::jsonb
);

-- Índices para feedback
CREATE INDEX IF NOT EXISTS idx_vrf_tienda ON visual_recognition_feedback(tienda_id);
CREATE INDEX IF NOT EXISTS idx_vrf_producto_sugerido ON visual_recognition_feedback(producto_sugerido_id);
CREATE INDEX IF NOT EXISTS idx_vrf_fue_correcto ON visual_recognition_feedback(fue_correcto);
CREATE INDEX IF NOT EXISTS idx_vrf_created_at ON visual_recognition_feedback(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_vrf_producto_rechazos 
  ON visual_recognition_feedback(producto_sugerido_id, fue_correcto) 
  WHERE fue_correcto = false;

COMMENT ON TABLE visual_recognition_feedback IS 'Almacena feedback de usuarios sobre reconocimiento visual para mejorar el modelo';
COMMENT ON COLUMN visual_recognition_feedback.fue_correcto IS 'true = usuario confirmó que el producto es correcto, false = usuario rechazó la sugerencia';
COMMENT ON COLUMN visual_recognition_feedback.embedding IS 'Vector de embedding capturado, útil para reentrenamiento del modelo';
