-- 001_schema.sql
-- Consolidated Schema Migration for Stockwear
-- Includes: Extensions, Tables, Indexes, Foreign Keys
-- Updated: 2026-01-10

-- ============================================================================
-- 1. EXTENSIONS
-- ============================================================================
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "postgis";
-- Optional: uncomment if using pgvector for embeddings
-- CREATE EXTENSION IF NOT EXISTS "vector";

-- ============================================================================
-- 2. TABLES
-- ============================================================================

-- 2.1 Tiendas (Multi-tenancy root)
CREATE TABLE IF NOT EXISTS tiendas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  logo_url TEXT,
  whatsapp TEXT,
  facebook TEXT,
  instagram TEXT,
  owner_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  sleep_schedule_enabled BOOLEAN DEFAULT FALSE,
  sleep_schedule_time TIME DEFAULT '22:00:00',
  wake_schedule_time TIME DEFAULT '07:00:00',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON COLUMN tiendas.sleep_schedule_enabled IS 'Indica si la desactivación automática de cuentas está habilitada';
COMMENT ON COLUMN tiendas.sleep_schedule_time IS 'Hora del día en que se desactivan automáticamente las cuentas (excepto el propietario)';
COMMENT ON COLUMN tiendas.wake_schedule_time IS 'Hora del día en que se permite nuevamente el acceso (fin del modo dormir)';

-- 2.2 Usuarios
CREATE TABLE IF NOT EXISTS usuarios (
  id UUID PRIMARY KEY,
  auth_uid UUID UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  nombre TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  telefono TEXT,
  rol TEXT NOT NULL CHECK (rol IN ('admin', 'empleado')),
  estado TEXT NOT NULL DEFAULT 'activo' CHECK (estado IN ('activo', 'inactivo')),
  tienda_id BIGINT REFERENCES tiendas(id),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW()),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

-- 2.3 Categorias
CREATE TABLE IF NOT EXISTS categorias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  estado TEXT NOT NULL DEFAULT 'activo',
  tienda_id BIGINT REFERENCES tiendas(id)
);

-- 2.4 Tallas
CREATE TABLE IF NOT EXISTS tallas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo TEXT NOT NULL CHECK (tipo IN ('numerico', 'alfanumerico')),
  nombre TEXT NOT NULL,
  estado TEXT NOT NULL DEFAULT 'activo',
  tienda_id BIGINT REFERENCES tiendas(id)
);

-- 2.5 Almacenes
CREATE TABLE IF NOT EXISTS almacenes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  direccion TEXT,
  tipo TEXT NOT NULL CHECK (tipo IN ('principal', 'sucursal')),
  estado TEXT NOT NULL DEFAULT 'activo',
  latitud DOUBLE PRECISION,
  longitud DOUBLE PRECISION,
  geom geography(Point, 4326),
  abreviatura TEXT,
  tienda_id BIGINT REFERENCES tiendas(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2.6 Productos
CREATE TABLE IF NOT EXISTS productos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo TEXT UNIQUE,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  "categoriaId" BIGINT REFERENCES categorias(id) ON DELETE RESTRICT,
  precio NUMERIC(12, 2) NOT NULL DEFAULT 0,
  precio_base NUMERIC(12, 2) DEFAULT 0,
  descuento NUMERIC(5, 2) NOT NULL DEFAULT 0,
  proveedor TEXT,
  marca TEXT,
  imagen TEXT,
  color TEXT,
  "stockMinimo" INTEGER NOT NULL DEFAULT 0,
  estado TEXT NOT NULL DEFAULT 'activo',
  tienda_id BIGINT REFERENCES tiendas(id),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW()),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

-- 2.7 Producto Reference Images
CREATE TABLE IF NOT EXISTS producto_reference_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "productoId" BIGINT NOT NULL REFERENCES productos(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  path TEXT NOT NULL,
  bucket TEXT,
  filename TEXT,
  "mimeType" TEXT,
  size BIGINT,
  tienda_id BIGINT REFERENCES tiendas(id),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW()),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

-- 2.8 Producto Embeddings
CREATE TABLE IF NOT EXISTS producto_embeddings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "productoId" BIGINT NOT NULL REFERENCES productos(id) ON DELETE CASCADE,
  embedding DOUBLE PRECISION[] NOT NULL,
  fuente TEXT,
  "referenceImageId" BIGINT REFERENCES producto_reference_images(id),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW()),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

-- 2.9 Stock
CREATE TABLE IF NOT EXISTS stock (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "productoId" BIGINT NOT NULL REFERENCES productos(id) ON DELETE CASCADE,
  "tallaId" BIGINT REFERENCES tallas(id) ON DELETE RESTRICT,
  "almacenId" BIGINT NOT NULL REFERENCES almacenes(id) ON DELETE RESTRICT,
  cantidad INTEGER NOT NULL DEFAULT 0,
  tienda_id BIGINT REFERENCES tiendas(id),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

-- 2.10 Historial Stock
CREATE TABLE IF NOT EXISTS "historialStock" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo TEXT NOT NULL CHECK (tipo IN ('entrada', 'salida', 'venta', 'ajuste')),
  "productoId" BIGINT NOT NULL REFERENCES productos(id) ON DELETE CASCADE,
  "tallaId" BIGINT REFERENCES tallas(id) ON DELETE RESTRICT,
  "almacenId" BIGINT NOT NULL REFERENCES almacenes(id) ON DELETE RESTRICT,
  cantidad INTEGER NOT NULL,
  "stockAnterior" INTEGER NOT NULL,
  "stockNuevo" INTEGER NOT NULL,
  "usuarioId" UUID REFERENCES usuarios(id) ON DELETE SET NULL,
  motivo TEXT,
  "costoUnitario" NUMERIC(12, 2),
  tienda_id BIGINT REFERENCES tiendas(id),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

-- 2.11 Consultas (Visual Recognition)
CREATE TABLE IF NOT EXISTS consultas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo TEXT NOT NULL CHECK (tipo IN ('reconocimiento_visual', 'manual')),
  "productoId" BIGINT REFERENCES productos(id) ON DELETE SET NULL,
  "empleadoId" UUID REFERENCES usuarios(id) ON DELETE SET NULL,
  "nivelConfianza" TEXT NOT NULL CHECK ("nivelConfianza" IN ('alto', 'medio', 'bajo')),
  resultado TEXT NOT NULL CHECK (resultado IN ('exitoso', 'fallido')),
  tienda_id BIGINT REFERENCES tiendas(id),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

-- 2.12 Clientes
CREATE TABLE IF NOT EXISTS clientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tienda_id BIGINT NOT NULL REFERENCES tiendas(id),
  nombre TEXT NOT NULL,
  documento TEXT,
  telefono TEXT,
  direccion TEXT,
  email TEXT,
  limite_credito NUMERIC DEFAULT 0,
  saldo_actual NUMERIC DEFAULT 0,
  estado TEXT DEFAULT 'activo' CHECK (estado IN ('activo', 'inactivo')),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW()),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

-- 2.13 Metodos de Pago
CREATE TABLE IF NOT EXISTS metodos_pago (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tienda_id BIGINT NOT NULL REFERENCES tiendas(id),
  nombre TEXT NOT NULL,
  tipo TEXT NOT NULL CHECK (tipo IN ('efectivo', 'digital', 'banco', 'tarjeta', 'otro')),
  estado TEXT NOT NULL DEFAULT 'activo' CHECK (estado IN ('activo', 'inactivo')),
  comision_porcentaje NUMERIC,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

-- 2.14 Caja Sesiones
CREATE TABLE IF NOT EXISTS caja_sesiones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tienda_id BIGINT NOT NULL REFERENCES tiendas(id),
  usuario_id UUID NOT NULL REFERENCES usuarios(id),
  monto_inicial NUMERIC(12, 2) NOT NULL DEFAULT 0,
  monto_final_esperado NUMERIC(12, 2),
  monto_final_real NUMERIC(12, 2),
  diferencia NUMERIC(12, 2),
  fecha_apertura TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW()),
  fecha_cierre TIMESTAMPTZ,
  estado TEXT NOT NULL DEFAULT 'abierta' CHECK (estado IN ('abierta', 'cerrada')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2.15 Ventas
CREATE TABLE IF NOT EXISTS ventas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folio TEXT UNIQUE,
  total NUMERIC(12, 2) NOT NULL DEFAULT 0,
  "usuarioId" UUID REFERENCES usuarios(id) ON DELETE SET NULL,
  tienda_id BIGINT REFERENCES tiendas(id),
  cliente_id BIGINT REFERENCES clientes(id),
  metodo_pago_id BIGINT REFERENCES metodos_pago(id),
  caja_sesion_id BIGINT REFERENCES caja_sesiones(id),
  tipo_venta TEXT DEFAULT 'contado' CHECK (tipo_venta IN ('contado', 'credito')),
  saldo_pendiente NUMERIC DEFAULT 0,
  numero_cuotas INTEGER DEFAULT 1,
  interes_porcentaje NUMERIC DEFAULT 0,
  monto_cuota NUMERIC DEFAULT 0,
  frecuencia_pago TEXT CHECK (frecuencia_pago IN ('semanal', 'mensual')),
  fecha_primer_vencimiento TIMESTAMPTZ,
  descripcion TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW()),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

-- 2.16 Ventas Detalle
CREATE TABLE IF NOT EXISTS "ventasDetalle" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ventaId" BIGINT NOT NULL REFERENCES ventas(id) ON DELETE CASCADE,
  "productoId" BIGINT NOT NULL REFERENCES productos(id) ON DELETE RESTRICT,
  "stockId" BIGINT NOT NULL REFERENCES stock(id) ON DELETE RESTRICT,
  cantidad INTEGER NOT NULL CHECK (cantidad > 0),
  "precioUnitario" NUMERIC(12, 2) NOT NULL CHECK ("precioUnitario" >= 0),
  "costoUnitario" NUMERIC(12, 2) DEFAULT 0,
  descuento NUMERIC(5, 2) NOT NULL DEFAULT 0,
  subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0,
  tienda_id BIGINT REFERENCES tiendas(id),
  created_at TIMESTAMPTZ DEFAULT timezone('utc', NOW())
);

-- 2.17 Abonos
CREATE TABLE IF NOT EXISTS abonos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tienda_id BIGINT NOT NULL REFERENCES tiendas(id),
  cliente_id BIGINT REFERENCES clientes(id),
  venta_id BIGINT REFERENCES ventas(id),
  monto NUMERIC NOT NULL CHECK (monto > 0),
  metodo_pago_id BIGINT REFERENCES metodos_pago(id),
  usuario_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  caja_sesion_id BIGINT REFERENCES caja_sesiones(id),
  nota TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

-- 2.18 Gastos
CREATE TABLE IF NOT EXISTS gastos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  tienda_id BIGINT NOT NULL REFERENCES tiendas(id),
  usuario_id UUID REFERENCES usuarios(id),
  caja_sesion_id BIGINT REFERENCES caja_sesiones(id),
  descripcion TEXT NOT NULL,
  monto NUMERIC NOT NULL,
  categoria TEXT NOT NULL,
  metodo_pago TEXT NOT NULL,
  proveedor TEXT,
  estado TEXT NOT NULL DEFAULT 'pagado' CHECK (estado IN ('pagado', 'pendiente')),
  saldo_pendiente NUMERIC NOT NULL DEFAULT 0,
  fecha_vencimiento TIMESTAMPTZ,
  fecha_gasto TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2.19 Pagos Gastos
CREATE TABLE IF NOT EXISTS pagos_gastos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  tienda_id BIGINT NOT NULL REFERENCES tiendas(id),
  gasto_id BIGINT NOT NULL REFERENCES gastos(id) ON DELETE CASCADE,
  usuario_id UUID REFERENCES usuarios(id),
  caja_sesion_id BIGINT REFERENCES caja_sesiones(id),
  monto NUMERIC NOT NULL,
  metodo_pago TEXT NOT NULL,
  nota TEXT,
  fecha_pago TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2.20 Search Feedback
CREATE TABLE IF NOT EXISTS search_feedback (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  query TEXT,
  product_id BIGINT REFERENCES productos(id),
  is_positive BOOLEAN,
  user_id UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2.21 Visual Recognition Feedback
CREATE TABLE IF NOT EXISTS visual_recognition_feedback (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  tienda_id INTEGER REFERENCES tiendas(id) ON DELETE CASCADE,
  empleado_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  producto_sugerido_id INTEGER REFERENCES productos(id) ON DELETE SET NULL,
  producto_correcto_id INTEGER REFERENCES productos(id) ON DELETE SET NULL,
  similitud FLOAT NOT NULL,
  umbral FLOAT NOT NULL,
  fue_correcto BOOLEAN NOT NULL,
  embedding FLOAT8[] DEFAULT NULL,
  metadata JSONB DEFAULT '{}'::jsonb
);

COMMENT ON TABLE visual_recognition_feedback IS 'Almacena feedback de usuarios sobre reconocimiento visual para mejorar el modelo';
COMMENT ON COLUMN visual_recognition_feedback.fue_correcto IS 'true = usuario confirmó que el producto es correcto, false = usuario rechazó la sugerencia';
COMMENT ON COLUMN visual_recognition_feedback.embedding IS 'Vector de embedding capturado, útil para reentrenamiento del modelo';

-- ============================================================================
-- 3. INDEXES
-- ============================================================================

-- Usuarios
CREATE INDEX IF NOT EXISTS usuarios_email_idx ON usuarios (email);
CREATE INDEX IF NOT EXISTS usuarios_auth_uid_idx ON usuarios (auth_uid);
CREATE INDEX IF NOT EXISTS idx_usuarios_tienda ON usuarios (tienda_id);

-- Productos
CREATE INDEX IF NOT EXISTS productos_nombre_idx ON productos USING GIN (to_tsvector('spanish', nombre));
CREATE INDEX IF NOT EXISTS productos_codigo_idx ON productos (LOWER(codigo));
CREATE INDEX IF NOT EXISTS idx_productos_tienda_categoria ON productos (tienda_id, "categoriaId");

-- Stock
CREATE INDEX IF NOT EXISTS stock_producto_idx ON stock ("productoId");
CREATE INDEX IF NOT EXISTS stock_almacen_idx ON stock ("almacenId");
CREATE INDEX IF NOT EXISTS stock_talla_idx ON stock ("tallaId");
CREATE INDEX IF NOT EXISTS idx_stock_producto_tienda ON stock (tienda_id, "productoId");
CREATE INDEX IF NOT EXISTS idx_stock_almacen_producto ON stock ("almacenId", "productoId");

-- Consultas
CREATE INDEX IF NOT EXISTS consultas_producto_idx ON consultas ("productoId");
CREATE INDEX IF NOT EXISTS consultas_empleado_idx ON consultas ("empleadoId");

-- Producto Reference Images
CREATE INDEX IF NOT EXISTS producto_reference_images_producto_idx ON producto_reference_images ("productoId");

-- Producto Embeddings
CREATE INDEX IF NOT EXISTS producto_embeddings_producto_idx ON producto_embeddings ("productoId");
CREATE INDEX IF NOT EXISTS producto_embeddings_reference_idx ON producto_embeddings ("referenceImageId");

-- Ventas
CREATE INDEX IF NOT EXISTS ventas_folio_idx ON ventas (folio);
CREATE INDEX IF NOT EXISTS ventas_usuario_idx ON ventas ("usuarioId");
CREATE INDEX IF NOT EXISTS idx_ventas_tienda ON ventas (tienda_id);
CREATE INDEX IF NOT EXISTS ventas_caja_sesion_idx ON ventas (caja_sesion_id);
CREATE INDEX IF NOT EXISTS ventas_metodo_pago_idx ON ventas (metodo_pago_id);

-- Ventas Detalle
CREATE INDEX IF NOT EXISTS ventas_detalle_venta_idx ON "ventasDetalle" ("ventaId");
CREATE INDEX IF NOT EXISTS ventas_detalle_producto_idx ON "ventasDetalle" ("productoId");

-- Almacenes
CREATE INDEX IF NOT EXISTS idx_almacenes_lat_long ON almacenes (latitud, longitud);
CREATE INDEX IF NOT EXISTS idx_almacenes_geom ON almacenes USING GIST (geom);

-- Caja Sesiones
CREATE INDEX IF NOT EXISTS idx_caja_tienda ON caja_sesiones (tienda_id);

-- Abonos
CREATE INDEX IF NOT EXISTS idx_abonos_cliente ON abonos (cliente_id);
CREATE INDEX IF NOT EXISTS abonos_caja_sesion_idx ON abonos (caja_sesion_id);

-- Gastos
CREATE INDEX IF NOT EXISTS idx_gastos_tienda ON gastos (tienda_id);

-- Historial Stock
CREATE INDEX IF NOT EXISTS idx_historial_producto ON "historialStock" ("productoId");
CREATE INDEX IF NOT EXISTS idx_historial_usuario ON "historialStock" ("usuarioId");

-- Visual Recognition Feedback
CREATE INDEX IF NOT EXISTS idx_vrf_tienda ON visual_recognition_feedback (tienda_id);
CREATE INDEX IF NOT EXISTS idx_vrf_producto_sugerido ON visual_recognition_feedback (producto_sugerido_id);
CREATE INDEX IF NOT EXISTS idx_vrf_fue_correcto ON visual_recognition_feedback (fue_correcto);
CREATE INDEX IF NOT EXISTS idx_vrf_created_at ON visual_recognition_feedback (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_vrf_producto_rechazos 
  ON visual_recognition_feedback (producto_sugerido_id, fue_correcto) 
  WHERE fue_correcto = false;

-- ============================================================================
-- 4. COLUMN ADDITIONS (Safe for existing databases)
-- ============================================================================

-- Tiendas
ALTER TABLE tiendas ADD COLUMN IF NOT EXISTS facebook TEXT;
ALTER TABLE tiendas ADD COLUMN IF NOT EXISTS instagram TEXT;
ALTER TABLE tiendas ADD COLUMN IF NOT EXISTS sleep_schedule_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE tiendas ADD COLUMN IF NOT EXISTS sleep_schedule_time TIME DEFAULT '22:00:00';
ALTER TABLE tiendas ADD COLUMN IF NOT EXISTS wake_schedule_time TIME DEFAULT '07:00:00';
ALTER TABLE tiendas ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- Productos
ALTER TABLE productos ADD COLUMN IF NOT EXISTS precio_base NUMERIC(12, 2) DEFAULT 0;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS marca TEXT;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS color TEXT;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMPTZ DEFAULT timezone('utc', NOW());

-- Ventas
ALTER TABLE ventas ADD COLUMN IF NOT EXISTS metodo_pago_id BIGINT REFERENCES metodos_pago(id);
ALTER TABLE ventas ADD COLUMN IF NOT EXISTS caja_sesion_id BIGINT REFERENCES caja_sesiones(id);
ALTER TABLE ventas ADD COLUMN IF NOT EXISTS descripcion TEXT;
ALTER TABLE ventas ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMPTZ DEFAULT timezone('utc', NOW());

-- Ventas Detalle
ALTER TABLE "ventasDetalle" ADD COLUMN IF NOT EXISTS "costoUnitario" NUMERIC(12, 2) DEFAULT 0;

-- Abonos
ALTER TABLE abonos ADD COLUMN IF NOT EXISTS caja_sesion_id BIGINT REFERENCES caja_sesiones(id);

-- Metodos Pago
ALTER TABLE metodos_pago ADD COLUMN IF NOT EXISTS comision_porcentaje NUMERIC;
