-- Ensure gastos has a primary key (fix for previous migration)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'gastos_pkey') THEN
        ALTER TABLE "public"."gastos" ADD PRIMARY KEY ("id");
    END IF;
END $$;

-- Create pagos_gastos table
create table if not exists "public"."pagos_gastos" (
    "id" bigint generated by default as identity not null,
    "tienda_id" bigint not null,
    "gasto_id" bigint not null references "public"."gastos"("id") on delete cascade,
    "usuario_id" uuid null,
    "caja_sesion_id" bigint null,
    "monto" numeric not null,
    "metodo_pago" text not null, -- 'Efectivo', 'Transferencia', 'Otro'
    "nota" text null,
    "fecha_pago" timestamp with time zone not null default now(),
    "created_at" timestamp with time zone not null default now()
);

alter table "public"."pagos_gastos" enable row level security;

create policy "Enable read access for all users"
on "public"."pagos_gastos"
as permissive
for select
to public
using (true);

create policy "Enable insert access for all users"
on "public"."pagos_gastos"
as permissive
for insert
to public
with check (true);
