-- Create gastos table
create table if not exists "public"."gastos" (
    "id" bigint generated by default as identity not null primary key,
    "tienda_id" bigint not null,
    "usuario_id" uuid null,
    "caja_sesion_id" bigint null,
    "descripcion" text not null,
    "monto" numeric not null,
    "categoria" text not null, -- 'Arriendo', 'Nómina', etc.
    "metodo_pago" text not null, -- 'Efectivo', 'Tarjeta', 'Transferencia', etc.
    "proveedor" text null,
    "estado" text not null default 'pagado', -- 'pagado', 'pendiente'
    "saldo_pendiente" numeric not null default 0,
    "fecha_vencimiento" timestamp with time zone null,
    "fecha_gasto" timestamp with time zone not null default now(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);

alter table "public"."gastos" enable row level security;

create policy "Enable read access for all users"
on "public"."gastos"
as permissive
for select
to public
using (true);

create policy "Enable insert access for all users"
on "public"."gastos"
as permissive
for insert
to public
with check (true);

create policy "Enable update access for all users"
on "public"."gastos"
as permissive
for update
to public
using (true);
