-- 1. Create Tiendas table
CREATE TABLE IF NOT EXISTS tiendas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL, -- For URL routing (e.g., stockwear.com/nike-store)
  logo_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Add tienda_id to existing tables
-- We use a function to safely add columns if they don't exist
DO $$
DECLARE
  t text;
BEGIN
  FOR t IN 
    SELECT unnest(ARRAY['usuarios', 'productos', 'categorias', 'tallas', 'almacenes', 'stock', 'historial_stock', 'ventas', 'venta_detalles', 'consultas'])
  LOOP
    EXECUTE 'ALTER TABLE ' || t || ' ADD COLUMN IF NOT EXISTS tienda_id BIGINT REFERENCES tiendas(id)';
  END LOOP;
END $$;

-- 3. Enable RLS on all tables (if not already enabled)
ALTER TABLE tiendas ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE tallas ENABLE ROW LEVEL SECURITY;
ALTER TABLE almacenes ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock ENABLE ROW LEVEL SECURITY;
ALTER TABLE historial_stock ENABLE ROW LEVEL SECURITY;
ALTER TABLE ventas ENABLE ROW LEVEL SECURITY;
ALTER TABLE venta_detalles ENABLE ROW LEVEL SECURITY;
ALTER TABLE consultas ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS Policies
-- Helper function to get current user's tienda_id
CREATE OR REPLACE FUNCTION get_my_tienda_id()
RETURNS BIGINT AS $$
  SELECT tienda_id FROM usuarios WHERE auth_uid = auth.uid() LIMIT 1;
$$ LANGUAGE sql SECURITY DEFINER;

-- Policy for Tiendas: Users can view their own tienda
CREATE POLICY "Users can view their own tienda" ON tiendas
  FOR SELECT USING (id = get_my_tienda_id());

-- Generic Policy Generator for other tables
-- "Users can view/edit records where tienda_id matches their own"
DO $$
DECLARE
  t text;
BEGIN
  FOR t IN 
    SELECT unnest(ARRAY['productos', 'categorias', 'tallas', 'almacenes', 'stock', 'historial_stock', 'ventas', 'venta_detalles', 'consultas'])
  LOOP
    EXECUTE format('
      DROP POLICY IF EXISTS "Tenant Isolation" ON %I;
      CREATE POLICY "Tenant Isolation" ON %I
      USING (tienda_id = get_my_tienda_id())
      WITH CHECK (tienda_id = get_my_tienda_id());
    ', t, t);
  END LOOP;
END $$;

-- Special Policy for Usuarios: Users can view other users in the same tienda
DROP POLICY IF EXISTS "Tenant Isolation" ON usuarios;
CREATE POLICY "Tenant Isolation" ON usuarios
  USING (tienda_id = (SELECT tienda_id FROM usuarios WHERE auth_uid = auth.uid() LIMIT 1))
  WITH CHECK (tienda_id = (SELECT tienda_id FROM usuarios WHERE auth_uid = auth.uid() LIMIT 1));

-- 5. Seed a default store (Optional, prevents breaking existing data)
INSERT INTO tiendas (nombre, slug) VALUES ('Tienda Principal', 'main') ON CONFLICT DO NOTHING;

-- Update existing records to belong to the default store (Safe to run multiple times)
UPDATE usuarios SET tienda_id = (SELECT id FROM tiendas WHERE slug = 'main') WHERE tienda_id IS NULL;
UPDATE productos SET tienda_id = (SELECT id FROM tiendas WHERE slug = 'main') WHERE tienda_id IS NULL;
UPDATE categorias SET tienda_id = (SELECT id FROM tiendas WHERE slug = 'main') WHERE tienda_id IS NULL;
UPDATE tallas SET tienda_id = (SELECT id FROM tiendas WHERE slug = 'main') WHERE tienda_id IS NULL;
UPDATE almacenes SET tienda_id = (SELECT id FROM tiendas WHERE slug = 'main') WHERE tienda_id IS NULL;
-- ... (Repeat for other tables if they have data)
